### ISSUE TITLE
about WTW data

### ISSUE THREAD

**Issue by backtime92** [naver-ai/trace#1]
Some of the WTW tabular data is wireless that some cell edge is wireless, did you filter these data？

**Comment by YoungminBaek** [comment]
No. I used the WTW tabular data as it is.
Therefore, the model trained on WTW can predict wired tables only.

**Comment by backtime92** [comment]
Thank you for your wonderful job.
one more question, are there any suitable tools to annotate such tabular data？
Or simply annotate the horizontal and vertical lines, and then obtain the structure through post-processing？

**Comment by YoungminBaek** [comment]
We used our own annotation tool for tabular data, allowing annotators to mark the invisibility of table edges.
To my knowledge, there is no publicly available tool like this.
